### ISSUE TITLE
API: ec2:RunInstances Not authorized for images: [ami-04ebd347ba3b42e14]

### ISSUE THREAD

**Issue by ThibaultWalterspieler** [aws-samples/aws-content-creation-render-environment-for-windows#8]
I'm trying to deploy the CloudFormation template in Frankfurt zone but I'm stuck with this error : 
<img width="2322" alt="Screenshot 2022-03-10 at 18 00 36" src="https://user-images.githubusercontent.com/15186627/157715664-3654c7d1-eb18-4d2e-92f2-01180bf317dc.png">
<img width="2410" alt="Screenshot 2022-03-10 at 18 01 00" src="https://user-images.githubusercontent.com/15186627/157715734-2e6a5104-66ad-4a8a-a419-085cb43c930f.png">

Any idea on how to solve this or where it could come from ? 

Cheers

**Comment by rezabekf** [comment]
We have just published new version which gets latest AMI id dynamically. Hope this solves any outstanding issues #9
